controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    publish_rate: 50.0
    left_wheel_names: ['left_wheel_fwd_joint', 'left_wheel_rear_joint']
    right_wheel_names: ['right_wheel_fwd_joint', 'right_wheel_rear_joint']
    wheels_per_side: 2
    wheel_separation: 0.2  # Update this to match the *total distance* between left and right sides
    wheel_radius: 0.05     # Update if your actual wheel radius differs
    base_frame_id: base_link
    use_stamped_vel: false

    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.0
    linear.x.min_velocity: 0.0
    linear.x.max_acceleration: 0.0
    linear.x.min_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.0
    angular.z.min_velocity: 0.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
